In [1]:
import pandas as pd

In [2]:
food_df = pd.read_csv("/content/food.csv")
food_nutrient_df = pd.read_csv("/content/food_nutrient.csv")
nutrient_df = pd.read_csv("/content/nutrient.csv")
foundation_food_df = pd.read_csv("/content/foundation_food.csv")

/tmp/ipykernel_3460/2813590165.py:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  food_nutrient_df = pd.read_csv("/content/food_nutrient.csv")

In [3]:
food_df.head(2)

,fdc_id,data_type,description,food_category_id,publication_date
0,319874,sample_food,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
1,319875,market_acquisition,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01

In [4]:
food_nutrient_df.head(2)

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
0,2201847,319877,1051,56.30,1.0,1.0,NaN,NaN,NaN,NaN,NaN
1,2201845,319877,1002,1.28,1.0,1.0,NaN,NaN,NaN,NaN,NaN

In [5]:
nutrient_df.head(2)

     id                               name unit_name  nutrient_nbr   rank
0  2047   Energy (Atwater General Factors)      KCAL         957.0  280.0
1  2048  Energy (Atwater Specific Factors)      KCAL         958.0  290.0

In [6]:
foundation_food_df.head()

   fdc_id  NDB_number                             footnote
0  321358       16158                                  NaN
1  321360      100147                                  NaN
2  321611       11056                                  NaN
3  323121        7022                                  NaN
4  323294       12563   Other phytosterols = 34.67 mg/100g

In [ ]:
import requests

def get_meals_by_macros(min_protein=40, max_fat=100, number_of_recipes=3):
    
    api_key = "448533b1425842039d118d4f6529ad6f"
    url = "https://api.spoonacular.com/recipes/findByNutrients"

    params = {
        "minProtein": min_protein,
        "maxFat": max_fat,
        "number": number_of_recipes,
        "apiKey": api_key
    }

    try:
        response = requests.get(url, params=params)
        if response.status_code == 200:
            recipes = response.json()

            cleaned_results = []
            for recipe in recipes:
                cleaned_results.append({
                    "Title": recipe["title"],
                    "Calories": recipe["calories"],
                    "Protein": recipe["protein"],
                    "Fat": recipe["fat"],
                    "Carbs": recipe["carbs"],
                    "Image": recipe["image"]
                })
            return cleaned_results
        else:
            return f"Error: {response.status_code} - {response.text}"

    except Exception as e:
        return f"An error occurred: {str(e)}"

suggested_meals = get_meals_by_macros(min_protein=40, max_fat=30)
print(suggested_meals)

[{'Title': 'Summertime Seafood Pie', 'Calories': 572, 'Protein': '69g', 'Fat': '18g', 'Carbs': '0g', 'Image': 'https://img.spoonacular.com/recipes/662271-312x231.jpg'}, {'Title': 'Slow Cooker Chili', 'Calories': 452, 'Protein': '50g', 'Fat': '11g', 'Carbs': '0g', 'Image': 'https://img.spoonacular.com/recipes/673457-312x231.jpg'}, {'Title': 'Instant Pot Pressure Cooker Pot Roast', 'Calories': 484, 'Protein': '51g', 'Fat': '9g', 'Carbs': '0g', 'Image': 'https://img.spoonacular.com/recipes/982375-312x231.jpg'}]

In [ ]:
foundation_ids = foundation_food_df['fdc_id'].unique()
food_filtered = food_df[food_df['fdc_id'].isin(foundation_ids)]


# 1008 = Energy (Calories), 1003 = Protein, 1004 = Total lipid (Fat), 1005 = Carbohydrate
macro_ids = [1008, 1003, 1004, 1005]
food_nutrient_filtered = food_nutrient_df[
    (food_nutrient_df['fdc_id'].isin(foundation_ids)) &
    (food_nutrient_df['nutrient_id'].isin(macro_ids))
]

merged_df = pd.merge(
    food_nutrient_filtered[['fdc_id', 'nutrient_id', 'amount']],
    food_filtered[['fdc_id', 'description']],
    on='fdc_id',
    how='inner'
)


pivot_df = merged_df.pivot_table(
    index=['fdc_id', 'description'],
    columns='nutrient_id',
    values='amount'
).reset_index()

# 1008 -> Calories, 1003 -> Protein, 1004 -> Fat, 1005 -> Carbs
pivot_df = pivot_df.rename(columns={
    1008: 'Calories_per_100g',
    1003: 'Protein_per_100g',
    1004: 'Fat_per_100g',
    1005: 'Carbs_per_100g'
})

pivot_df = pivot_df.fillna(0)

pivot_df.to_csv('egyptian_agents_food_db.csv', index=False)

✅ اللعبة اتقفلت بنجاح! تم إنشاء ملف: egyptian_agents_food_db.csv
📊 إجمالي المكونات الخام الجاهزة للاستخدام: 355 مكون.

In [8]:
pivot_df

nutrient_id,fdc_id,description,Protein_per_100g,Fat_per_100g,Carbs_per_100g,Calories_per_100g
0,321358,"Hummus, commercial",7.350000,17.1000,14.900000,229.0
1,321360,"Tomatoes, grape, raw",0.830000,0.6300,5.510000,27.0
2,321611,"Beans, snap, green, canned, regular pack, drai...",1.040000,0.3900,4.110000,21.0
3,323121,"Frankfurter, beef, unheated",11.700000,28.0000,2.890000,314.0
4,323294,"Nuts, almonds, dry roasted, with salt added",20.400000,57.8000,16.200000,620.0
...,...,...,...,...,...,...
350,2747673,"Tuna, ahi or yellowfin, frozen, wild caught",24.700000,0.3875,-0.104500,0.0
351,2747674,"Turnips, raw",0.953125,0.1188,7.274975,0.0
352,2747675,"Watermelon, seedless, flesh only, raw",0.871250,0.0000,0.000000,0.0
353,2747676,"Watermelon, seedless, rind only, raw",0.531250,0.0700,4.166000,0.0
354,2768188,"Alaska Pollock, raw",17.330000,0.9925,0.056500,0.0

In [11]:
pivot_df["description"].unique()

array(['Hummus, commercial', 'Tomatoes, grape, raw',
       'Beans, snap, green, canned, regular pack, drained solids',
       'Frankfurter, beef, unheated',
       'Nuts, almonds, dry roasted, with salt added', 'Kale, raw',
       'Egg, whole, raw, frozen, pasteurized',
       'Egg, white, raw, frozen, pasteurized', 'Egg, white, dried',
       'Onion rings, breaded, par fried, frozen, prepared, heated in oven',
       'Pickles, cucumber, dill or kosher dill',
       'Cheese, parmesan, grated',
       'Cheese, pasteurized process, American, vitamin D fortified',
       'Grapefruit juice, white, canned or bottled, unsweetened',
       'Peaches, yellow, raw',
       'Seeds, sunflower seed kernels, dry roasted, with salt added',
       'Kale, frozen, cooked, boiled, drained, without salt',
       'Mustard, prepared, yellow', 'Kiwifruit, green, raw',
       'Nectarines, raw', 'Cheese, cheddar',
       'Cheese, cottage, lowfat, 2% milkfat',
       'Cheese, mozzarella, low moisture, part-skim', 'Egg, whole, dried',
       'Egg, yolk, raw, frozen, pasteurized', 'Egg, yolk, dried',
       'Yogurt, Greek, plain, nonfat',
       'Yogurt, Greek, strawberry, nonfat', 'Oil, coconut',
       'Chicken, broilers or fryers, drumstick, meat only, cooked, braised',
       'Chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, braised',
       'Sauce, pasta, spaghetti/marinara, ready-to-serve',
       'Ham, sliced, pre-packaged, deli meat (96%fat free, water added)',
       'Olives, green, Manzanilla, stuffed with pimiento',
       'Cookies, oatmeal, soft, with raisins',
       'Tomatoes, canned, red, ripe, diced', 'Fish, haddock, raw',
       'Fish, pollock, raw',
       'Fish, tuna, light, canned in water, drained solids',
       'Restaurant, Chinese, fried rice, without meat',
       'Restaurant, Latino, tamale, pork',
       'Restaurant, Latino, pupusas con frijoles (pupusas, bean)',
       'Beef, loin, tenderloin roast, separable lean only, boneless, trimmed to 0" fat, select, cooked, roasted',
       'Beef, loin, top loin steak, boneless, lip-on, separable lean only, trimmed to 1/8" fat, choice, raw',
       'Beef, round, eye of round roast, boneless, separable lean only, trimmed to 0" fat, select, raw',
       'Beef, round, top round roast, boneless, separable lean only, trimmed to 0" fat, select, raw',
       'Beef, short loin, porterhouse steak, separable lean only, trimmed to 1/8" fat, select, raw',
       'Beef, short loin, t-bone steak, bone-in, separable lean only, trimmed to 1/8" fat, choice, cooked, grilled',
       'Carrots, frozen, unprepared', 'Cheese, dry white, queso seco',
       'Cheese, ricotta, whole milk', 'Cheese, swiss',
       'Figs, dried, uncooked', 'Lettuce, cos or romaine, raw',
       'Melons, cantaloupe, raw', 'Oranges, raw, navels',
       'Milk, lowfat, fluid, 1% milkfat, with added vitamin A and vitamin D',
       'Pears, raw, bartlett', 'Restaurant, Chinese, sweet and sour pork',
       'Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)',
       'Sauce, salsa, ready-to-serve',
       'Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D',
       'Sausage, breakfast sausage, beef, pre-cooked, unprepared',
       'Sausage, Italian, pork, mild, cooked, pan-fried',
       'Sausage, pork, chorizo, link or ground, cooked, pan-fried',
       'Milk, whole, 3.25% milkfat, with added vitamin D',
       'Sausage, turkey, breakfast links, mild, raw',
       'Sugars, granulated',
       'Turkey, ground, 93% lean, 7% fat, pan-broiled crumbles',
       'Ham, sliced, restaurant', 'Cheese, American, restaurant',
       'Beans, Dry, Medium Red (0% moisture)',
       'Beans, Dry, Red (0% moisture)',
       'Beans, Dry, Flor de Mayo (0% moisture)',
       'Beans, Dry, Brown (0% moisture)', 'Beans, Dry, Tan (0% moisture)',
       'Beans, Dry, Light Tan (0% moisture)',
       'Beans, Dry, Carioca (0% moisture)',
       'Beans, Dry, Cranberry (0% moisture)',
       'Beans, Dry, Light Red Kidney (0% moisture)',
       'Beans, Dry, Pink (0% moisture)',
       'Beans, Dry, Dark Red Kidney (0% moisture)',
       'Beans, Dry, Navy (0% moisture)',
       'Beans, Dry, Small White (0% moisture)',
       'Beans, Dry, Small Red (0% moisture)',
       'Beans, Dry, Black (0% moisture)',
       'Beans, Dry, Pinto (0% moisture)',
       'Beans, Dry, Great Northern (0% moisture)', 'Broccoli, raw',
       'Ketchup, restaurant', 'Eggs, Grade A, Large, egg white',
       'Eggs, Grade A, Large, egg yolk',
       'Eggs, Grade A, Large, egg whole',
       'Pork, cured, bacon, cooked, restaurant',
       'Butter, stick, unsalted',
       'Flour, wheat, all-purpose, enriched, bleached',
       'Flour, wheat, all-purpose, enriched, unbleached',
       'Flour, wheat, all-purpose, unenriched, unbleached',
       'Flour, whole wheat, unenriched',
       'Flour, bread, white, enriched, unbleached',
       'Flour, rice, white, unenriched',
       'Flour, corn, yellow, fine meal, enriched',
       'Butter, stick, salted', 'Onions, red, raw', 'Onions, yellow, raw',
       'Garlic, raw', 'Flour, soy, defatted', 'Flour, soy, full-fat',
       'Flour, rice, brown', 'Flour, rice, glutinous',
       'Flour, pastry, unenriched, unbleached', 'Onions, white, raw',
       'Bananas, overripe, raw', 'Bananas, ripe and slightly ripe, raw',
       'Apples, red delicious, with skin, raw',
       'Apples, fuji, with skin, raw', 'Apples, gala, with skin, raw',
       'Apples, granny smith, with skin, raw',
       'Apples, honeycrisp, with skin, raw', "Mushroom, lion's mane",
       'Mushroom, oyster', 'Mushrooms, shiitake',
       'Mushrooms, white button',
       'Soy milk, unsweetened, plain, shelf stable',
       'Almond milk, unsweetened, plain, shelf stable', 'Spinach, baby',
       'Spinach, mature', 'Tomato, roma', 'Flour, 00',
       'Flour, spelt, whole grain',
       'Flour, semolina, coarse and semi-coarse', 'Flour, semolina, fine',
       'Apple juice, with added vitamin C, from concentrate, shelf stable',
       'Orange juice, no pulp, not fortified, from concentrate, refrigerated',
       'Grape juice, purple, with added vitamin C, from concentrate, shelf stable',
       'Grape juice, white, with added vitamin C, from concentrate, shelf stable',
       'Cranberry juice, not fortified, from concentrate, shelf stable',
       'Grapefruit juice, red, not fortified, not from concentrate, refrigerated',
       'Tomato juice, with added ingredients, from concentrate, shelf stable',
       'Orange juice, no pulp, not fortified, not from concentrate, refrigerated',
       'Mushroom, portabella', 'Mushroom, king oyster', 'Mushroom, enoki',
       'Mushroom, crimini', 'Mushroom, maitake', 'Mushroom, beech',
       'Mushroom, pioppini', 'Soy milk, sweetened, plain, refrigerated',
       'Almond milk, unsweetened, plain, refrigerated',
       'Oat milk, unsweetened, plain, refrigerated',
       'Carrots, mature, raw', 'Carrots, baby, raw',
       'Peppers, bell, green, raw', 'Peppers, bell, yellow, raw',
       'Peppers, bell, red, raw', 'Peppers, bell, orange, raw',
       'Buttermilk, low fat', 'Yogurt, plain, whole milk',
       'Yogurt, Greek, plain, whole milk',
       'Cheese, parmesan, grated, refrigerated',
       'Cheese, feta, whole milk, crumbled', 'Flour, almond',
       'Flour, oat, whole grain', 'Flour, potato',
       'Peanut butter, creamy', 'Sesame butter, creamy',
       'Almond butter, creamy', 'Flaxseed, ground',
       'Cottage cheese, full fat, large or small curd',
       'Cream cheese, full fat, block', 'Cream, heavy',
       'Cream, sour, full fat', 'Lettuce, iceberg, raw',
       'Lettuce, romaine, green, raw', 'Lettuce, leaf, red, raw',
       'Lettuce, leaf, green, raw', 'Nuts, pine nuts, raw',
       'Nuts, almonds, whole, raw', 'Nuts, walnuts, English, halves, raw',
       'Nuts, pecans, halves, raw',
       'Oats, whole grain, rolled, old fashioned',
       'Oats, whole grain, steel cut', 'Pineapple, raw',
       'Cherries, sweet, dark red, raw', 'Beans, snap, green, raw',
       'Potatoes, russet, without skin, raw',
       'Potatoes, red, without skin, raw',
       'Potatoes, gold, without skin, raw',
       'Sweet potatoes, orange flesh, without skin, raw', 'Celery, raw',
       'Cucumber, with peel, raw', 'Cabbage, green, raw',
       'Cabbage, red, raw', 'Strawberries, raw', 'Raspberries, raw',
       'Blueberries, raw', 'Grapes, red, seedless, raw',
       'Grapes, green, seedless, raw',
       'Applesauce, unsweetened, with added vitamin C', 'Flour, amaranth',
       'Flour, quinoa', 'Flour, sorghum', 'Flour, buckwheat',
       'Flour, rye', 'Flour, barley', 'Flour, cassava',
       'Buckwheat, whole grain', 'Millet, whole grain',
       'Rice, brown, long grain, unenriched, raw',
       'Rice, white, long grain, unenriched, raw',
       'Beef, ground, 90% lean meat / 10% fat, raw',
       'Beef, ground, 80% lean meat / 20% fat, raw', 'Pork, ground, raw',
       'Chicken, ground, with additives, raw',
       'Turkey, ground, 93% lean/ 7% fat, raw', 'Nuts, brazilnuts, raw',
       'Nuts, cashew nuts, raw', 'Nuts, hazelnuts or filberts, raw',
       'Peanuts, raw', 'Flour, chestnut', 'Nuts, macadamia nuts, raw',
       'Nuts, pistachio nuts, raw', 'Seeds, pumpkin seeds (pepitas), raw',
       'Seeds, sunflower seed, kernel, raw', 'Flour, coconut',
       'Beans, cannellini, dry',
       'Chickpeas, (garbanzo beans, bengal gram), dry', 'Lentils, dry',
       'Blackeye pea, dry',
       'Beans, black, canned, sodium added, drained and rinsed',
       'Beans, navy, canned, sodium added, drained and rinsed',
       'Beans, cannellini, canned, sodium added, drained and rinsed',
       'Chickpeas (garbanzo beans, bengal gram), canned, sodium added, drained and rinsed',
       'Beans, kidney, dark red, canned, sodium added, sugar added, drained and rinsed',
       'Beans, kidney, light red, canned, sodium added, sugar added, drained and rinsed',
       'Peas, green, sweet, canned, sodium added, sugar added, drained and rinsed',
       'Beans, pinto, canned, sodium added, drained and rinsed',
       'Blackeye pea, canned, sodium added, drained and rinsed',
       'Beans, great northern, canned, sodium added, drained and rinsed',
       'Pork, loin, boneless, raw',
       'Pork, loin, tenderloin, boneless, raw',
       'Chicken, breast, boneless, skinless, raw',
       'Chicken, thigh, boneless, skinless, raw',
       'Beef, ribeye, steak, boneless, choice, raw',
       'Beef, round, top round, boneless, choice, raw',
       'Beef, chuck, roast, boneless, choice, raw',
       'Beef, flank, steak, boneless, choice, raw',
       'Yogurt, plain, nonfat', 'Cheese, monterey jack, solid',
       'Cheese, pasteurized process cheese food or product, American, singles',
       'Cheese, provolone, sliced', 'Cheese, oaxaca, solid',
       'Cheese, queso fresco, solid', 'Cheese, cotija, solid',
       'Fish, salmon, sockeye, wild caught, raw',
       'Fish, salmon, Atlantic, farm raised, raw',
       'Fish, tilapia, farm raised, raw',
       'Crustaceans, shrimp, farm raised, raw',
       'Fish, cod, Atlantic, wild caught, raw',
       'Fish, catfish, farm raised, raw',
       'Crustaceans, crab, blue swimming, lump, pasteurized, refrigerated',
       'Squash, summer, green, zucchini, includes skin, raw',
       'Squash, summer, yellow, includes skin, raw',
       'Squash, winter, butternut, raw', 'Squash, winter, acorn, raw',
       'Cabbage, bok choy, raw', 'Cauliflower, raw', 'Collards, raw',
       'Brussels sprouts, raw', 'Beets, raw', 'Eggplant, raw',
       'Tomatoes, whole, canned, solids and liquids, with salt added',
       'Tomato, sauce, canned, with salt added',
       'Tomato, paste, canned, without salt added',
       'Tomatoes, crushed, canned', 'Tomato, puree, canned',
       'Apricot, with skin, raw', 'Melons, honeydew, raw',
       'Plantains, ripe, raw', 'Plantains, underripe, raw',
       'Chia seeds, dry, raw', 'Bulgur, dry, raw', 'Wild rice, dry, raw',
       'Arugula, baby, raw', 'Asparagus, green, raw',
       'Avocado, Hass, peeled, raw', 'Rice, black, unenriched, raw',
       'Corn, sweet, yellow and white kernels, \xa0fresh, raw',
       'Einkorn, grain, dry, raw', 'Farro, pearled, dry, raw',
       'Fonio, grain, dry, raw', 'Khorasan, grain, dry, raw',
       'Kiwifruit (kiwi), green, peeled, raw',
       'Mandarin, seedless, peeled, raw',
       'Mango, Tommy Atkins, peeled, raw', 'Mango, Ataulfo, peeled, raw',
       'Corn flour, masa harina, white or yellow, dry, raw',
       'Pear, Anjou, green, with skin, raw',
       'Plum, black, with skin, raw', 'Rice, red, unenriched, dry, raw',
       'Sorghum bran, white, unenriched, dry, raw',
       'Sorghum flour, white, pearled, unenriched, dry, raw',
       'Sorghum grain, white, pearled, unenriched, dry, raw',
       'Sorghum, whole grain, white, dry, raw',
       'Plantains, overripe, raw',
       'Chicken, drumstick, meat and skin, raw',
       'Chicken, thigh, meat and skin, raw',
       'Chicken, wing, meat and skin, raw',
       'Chicken, breast, meat and skin, raw', 'Lamb, ground, raw',
       'Bison, ground, raw', 'Beef, short loin (NY strip steak), raw',
       'Beef,\xa0tenderloin steak, raw', 'Beef, top sirloin steak, raw',
       'Pork, chop, center cut, raw', 'Pork, belly, with skin, raw',
       'Pawpaw, peeled, seeded, raw',
       'Squash, pie pumpkin, peeled, seeded, raw',
       'Squash, spaghetti, peeled, seeded, raw', 'Rutabaga, peeled, raw',
       'Blackberries, raw', 'Tomatillos, dehusked, raw',
       'Cabbage, napa, leaf, destemmed, raw',
       'Leeks, bulb and greens, root removed, raw',
       'Green onion, (scallion), bulb and greens, root removed, raw',
       'Shallots, bulb, peeled, root removed, raw',
       'Juice, prune, shelf-stable',
       'Juice, pomegranate, from concentrate, shelf-stable',
       'Juice, tart cherry, from concentrate, shelf-stable',
       'Anchovies, canned in olive oil, with salt, drained',
       'Beet greens, raw', 'Cod, Pacific or Alaskan, frozen, wild caught',
       'Fennel, bulb, raw', 'Halibut, frozen, wild caught',
       'Lobster, tail only, frozen, wild caught',
       'Mahi mahi, frozen, wild caught', 'Parsnips, raw',
       'Peppers, banana or Hungarian wax, seeded, raw',
       'Peppers, jalapeno, seeded, raw', 'Peppers, poblano, seeded, raw',
       'Peppers, serrano, seeded, raw', 'Radicchio, raw',
       'Radishes, red, raw',
       'Scallops, bay, Patagonian, frozen, wild caught',
       'Scallops, sea, frozen, wild caught',
       'Sea bass, Chilean, frozen, wild caught',
       'Snapper, frozen, wild caught', 'Snow crab, legs only, frozen  ',
       'Squid (calamari), frozen, tubes only',
       'Swordfish, frozen, wild caught',
       'Tuna, ahi or yellowfin, frozen, wild caught', 'Turnips, raw',
       'Watermelon, seedless, flesh only, raw',
       'Watermelon, seedless, rind only, raw', 'Alaska Pollock, raw'],
      dtype=object)

In [14]:
def search_food_macros(food_name):
    """أداة للـ Agent عشان يبحث في قاعدة البيانات المحلية عن ماكروز أي أكلة"""
    df = pd.read_csv('/content/egyptian_agents_food_db.csv')

    # البحث بالاسم (case-insensitive)
    results = df[df['description'].str.contains(food_name, case=False, na=False)]

    output = []
    for _, row in results.head(5).iterrows(): # هيرجع أول 5 نتائج مطابقة بس
        output.append({
            "Food": row['description'],
            "Calories_100g": row['Calories_per_100g'],
            "Protein_100g": row['Protein_per_100g'],
            "Fat_100g": row['Fat_per_100g'],
            "Carbs_100g": row['Carbs_per_100g']
        })
    return output

# تجربة الأدآة:
print(search_food_macros("Cottage"))

[{'Food': 'Cheese, cottage, lowfat, 2% milkfat', 'Calories_100g': 84.0, 'Protein_100g': 11.0, 'Fat_100g': 2.3, 'Carbs_100g': 4.31}, {'Food': 'Cottage cheese, full fat, large or small curd', 'Calories_100g': 0.0, 'Protein_100g': 11.62436, 'Fat_100g': 4.225, 'Carbs_100g': 4.59964}]